nodes:
- input.visual:
    source: raws/overhead_3.mp4
- model.yolo:
    detect: ["person"]
- custom_nodes.dabble.bbox_to_mid_midpoint
- dabble.zone_count:
    resolution: [640, 352]
    zones: [[[0.0, 0.0], [0.5, 0.0], [0.5, 0.5], [0.0, 0.5]], [[0.0, 0.5], [0.5, 0.5], [0.5, 1.0], [0.0, 1.0]], [[0.5, 0.0], [1.0, 0.0], [1.0, 0.5], [0.5, 0.5]], [[0.5, 0.5], [1.0, 0.5], [1.0, 1.0], [0.5, 1.0]]]
- custom_nodes.draw.img_tint_test:
    rows: 2
    columns: 2
- draw.bbox
- draw.btm_midpoint
- draw.zones
- draw.legend:
    show : ["zone_count"]
- output.screen
- output.media_writer:
    output_dir : output/
