nodes:
- input.visual:
    source: raws/candidate_5_2.mp4
- model.yolo:
    detect: ["person"]
- custom_nodes.dabble.bbox_to_mid_midpoint
- dabble.zone_count:
    resolution: [848, 480]
    zones: [[[0.0, 0.333], [1.0, 0.333], [1.0, 0.666], [0.0, 0.666]], [[0.0, 0.666], [1.0, 0.666], [1.0, 0.9990000000000001], [0.0, 0.9990000000000001]]]
- custom_nodes.draw.img_tint_test:
    rows: 3
    columns: 1
- draw.bbox
- draw.btm_midpoint
- draw.zones
- draw.legend:
    show : ["zone_count"]
- output.screen
- output.media_writer:
    output_dir : output/
